spring:
    application:
        name: TrackingApp
#    web:
#      resources:
#        static-locations: classpath:/html/
    datasource:
#      url: jdbc:postgresql://localhost:5432/postgres
      url: jdbc:postgresql://database:5432/tracking-app
      username: postgres
      password: privet
      driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
jwt:
    secret-key: "myq32qcharacterqultraqsecureqandqultraqlongqsecret"
    access-expire: "900000"
    refresh-expire: "25200000"
#    security:
#      oauth2:
#        client:
#            registration:
#              google:
#                  client-id: "219687961906-maid8qanmgk7ttv7uiqip5lnt0378ah3.apps.googleusercontent.com"
#                  client-secret: "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"
#                  redirect-uri: "http://localhost:8080/login/oauth2/code/google"